# Generated by Django 5.1.2 on 2024-11-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHealthMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Дата и время последнего замера умными носимыми устройствами', verbose_name='Дата и время последнего замера')),
                ('systolic_pressure', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Систолическое давление')),
                ('diastolic_pressure', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Диастолическое давление')),
                ('pulse', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Пульс')),
                ('temperature', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Температура')),
                ('steps', models.IntegerField(verbose_name='Количество шагов')),
                ('stress_level', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Уровень стресса')),
                ('oxygen_level', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Уровень кислорода в крови')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Последний замер показателей здоровья',
                'verbose_name_plural': 'Последние замеры показателей здоровья',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHealthReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField(auto_now=True, help_text='Дата диспансеризации и проведения контрольных замеров', verbose_name='Дата контрольного замера')),
                ('blood_group', models.PositiveSmallIntegerField(verbose_name='Группа крови')),
                ('rhesus_factor', models.BooleanField(verbose_name='Резус-фактор')),
                ('normal_systolic_pressure', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Эталонное систолическое давление')),
                ('normal_diastolic_pressure', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Эталонное диастолическое давление')),
                ('normal_pulse', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Эталонный пульс')),
                ('normal_temperature', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Эталонная температура')),
                ('normal_steps', models.IntegerField(verbose_name='Эталонное количество шагов')),
                ('normal_stress_level', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Эталонный уровень стресса')),
                ('normal_oxygen_level', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Эталонный уровень кислорода в крови')),
            ],
            options={
                'verbose_name': 'Эталонное значение показателей здоровья',
                'verbose_name_plural': 'Эталонные значения показателей здоровья',
            },
        ),
    ]
